export const
    SET_PROFILE = "SET_PROFILE",
    SET_ALERT = "SET_ALERT",
    RESET_ALERT = "RESET_ALERT",
    SET_TASKS = "SET_TASKS",
    SET_ADD_MODAL = "SET_ADD_MODAL",
    RESET_ADD_MODAL = "RESET_ADD_MODAL",
    SET_EDIT_MODAL = "SET_EDIT_MODAL",
    RESET_EDIT_MODAL = "RESET_EDIT_MODAL",
    SET_OTP_MODAL = "SET_OTP_MODAL",
    RESET_OTP_MODAL = "RESET_OTP_MODAL",
    SET_PROF_EDIT_DATA = "SET_PROF_EDIT_DATA"
    
